dubbo:
  application:
    name: dubbo-provider-2
    version: 1.0
  protocol:
    name: dubbo
    port: 20882
  provider:
    timeout: 60000
    filter: tracing # 这里必须配置 filter 否则链路跟踪会不生效，因为 TracingFilter不是默认激活的，是在url中包含 tracing 才会激活的
  registry:
    address: zookeeper://139.196.140.168:2181
server:
  port: 9092
spring:
  application:
    name: dubbo-provider-2
management:
  endpoints:
    web:
      exposure:
        include: "*"