dubbo:
  application:
    name: dubbo-provider
    version: 1.0
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 60000
  registry:
    address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
server:
  port: 9091
spring:
  application:
    name: dubbo-provider-demo
