dubbo:
  application:
    name: dubbo-provider
    version: 1.0
  protocol:
    name: dubbo
    port: 20881
  provider:
    timeout: 60000
  registry:
    address: zookeeper://139.196.140.168:2181?backup=139.196.140.168:2182,139.196.140.168:2183
server:
  port: 9091
spring:
  application:
    name: dubbo-provider-demo
