spring:
  application:
    name: dubbo-consumer-demo
server:
  port: 9092
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://139.196.140.168:2181?backup=139.196.140.168:2182,139.196.140.168:2183
  consumer:
    check: false
    filter: tracing # 这里必须配置 filter 否则链路跟踪会不生效，因为 TracingFilter不是默认激活的，是在url中包含 tracing 才会激活的
