spring:
  application:
    name: dubbo-consumer-demo
server:
  port: 9092
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://139.196.140.168:2181?backup=139.196.140.168:2182,139.196.140.168:2183
  consumer:
    check: false
    filter: tracing
